baseURL = "http://example.org/"
languageCode = "ja"
title = "My Favorite Pokemon"
theme = "Anatole"
contentDir = "content"
publishDir = "docs"
hasCJKLanguage = true
summaryLength = 0

[params]
title = "かわいいポケモン"
author = "cute"
description = "お気に入りのポケモンを紹介します"
profilePicture = " images / https://user-images.githubusercontent.com/83796113/118065518-1154a580-b3d8-11eb-9703-992335827fea.png "
